import type { Metadata } from "next";
import { Gemunu_Libre} from "next/font/google";
import "./globals.css";
import {   UserDataProvider } from "./context/UserContext";

const gemuni_libre  = Gemunu_Libre({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${gemuni_libre.className} h-screen w-screen `}>
   <UserDataProvider>
   
   {children}



   </UserDataProvider>

        
        </body>
    </html>
  );
}
